services:
  burp-uploader:
    build: .
    container_name: burpscan-uploader
    env_file:
      - .env
    volumes:
      - ./$BURP_REPORT:/app/burp_report.xml:ro
    restart: "no"  # Prevents container from restarting
    command: ["/app/burp_uploader.sh"]
