services:
  burp-uploader:
    build: .
    container_name: burpscan-uploader
    env_file:
      - .env
    volumes:
      - ./burp_report.xml:/app/burp_report.xml:ro
    restart: "no"  # Prevents container from restarting
    command: ["/app/burp_upload.sh"]
